// ============================================================================
//  ONE FILE. Paste this OVER the whole contents of the project's existing .gs
//  file: click into it, select all, paste. Do NOT add a second file — every
//  .gs in an Apps Script project shares one global scope, so a leftover copy
//  fails with
//
//      SyntaxError: Identifier 'TITLE' has already been declared
//
//  before a single line runs. Updating later means pasting over this same
//  file again, never alongside it.
//
//  DO NOT DEPLOY THIS. It is not a web app.
//
//  Run it from this editor:
//    1. pick `setup` in the function dropdown next to the Run button
//    2. click Run, and allow the authorization prompt (Forms, Drive, Sheets)
//    3. read the URL out of the Execution log at the bottom
//
//  Deploy > New deployment is the wrong path: a web app needs a doGet(e),
//  this has none, and you get "Script function not found: doGet".
//  This script CREATES a Google Form. The form has the URL you share; the
//  script is only what builds it, and it is finished the moment it has run.
// ============================================================================
//
// GENERATED by `ctsx collect:render` from collector/questions/expert-intake.yaml v2
// — do not edit. Regenerate instead.
//
// One form for every industry; the industry is the first question. Runs as you, under your
// own account: no Cloud project, no OAuth client, no admin approval.
//
// Safe to re-run, and re-running is the whole update path. Adding an industry to
// taxonomy/industries.yaml means: re-render, paste this over the old script, Run setup.
// Same form, same URL, same responses — only the dropdown grows.

const TITLE = "commercetools spec collector — industry intake";
const DESCRIPTION = "Pick your industry, then tell us what a bare storefront is missing for it. Three boxes, about three minutes. Your answers become reviewed spec drafts that every build for that industry then starts from. Please do not name a customer you are under NDA with — describe the pattern instead.";

// The questionnaire, in order. Kept as data so setup() can compare it against the live form
// item by item instead of assuming what is there.
const QUESTIONS = [
  { kind: "LIST", required: true,
    title: "Which industry are you answering about?",
    help: "One industry per submission. If two of them are yours, please send the form twice — the answers are filed separately.",
    choices: ["Grocery & q-commerce","Telecommunications","Fashion & apparel","Something else — I'll name it in the boxes below"] },
  { kind: "CHECKBOX", required: true,
    title: "Which business models have you seen this industry run as?",
    help: "",
    choices: ["B2C","B2B","B2B2C","B2B2B"] },
  { kind: "PARAGRAPH_TEXT", required: true,
    title: "Feature 1: what would you add to a bare storefront to make it work for the industry you picked?",
    help: "One capability per box. Name it, then say why that industry specifically needs it.",
    choices: null },
  { kind: "PARAGRAPH_TEXT", required: false,
    title: "Feature 2: what would you add to a bare storefront to make it work for the industry you picked?",
    help: "One capability per box. Name it, then say why that industry specifically needs it.",
    choices: null },
  { kind: "PARAGRAPH_TEXT", required: false,
    title: "Feature 3: what would you add to a bare storefront to make it work for the industry you picked?",
    help: "One capability per box. Name it, then say why that industry specifically needs it.",
    choices: null },
  { kind: "CHECKBOX", required: false,
    title: "Which areas do your features touch?",
    help: "",
    choices: ["Catalog & product data","Search & discovery","Cart & basket","Pricing & promotions","Checkout & payment","Shipping & fulfillment","Order management","Customers & accounts","Credit & receivables","Other"] },
  { kind: "TEXT", required: false,
    title: "A retailer or competitor doing this well (optional)",
    help: "No customer names under NDA — describe the pattern instead.",
    choices: null },
];

// Find the form we made last time, if any. getFilesByName also returns TRASHED files and
// files of any type, so a deleted form would otherwise come back from the bin, and a
// same-named document would crash openById.
function findExistingForm() {
  const files = DriveApp.getFilesByName(TITLE);
  while (files.hasNext()) {
    const file = files.next();
    if (file.isTrashed()) continue;
    if (file.getMimeType() !== MimeType.GOOGLE_FORMS) continue;
    return FormApp.openById(file.getId());
  }
  return null;
}

// An ItemType enum member as the plain name QUESTIONS uses. Compared member by member on
// purpose: indexing the enum or stringifying it are both assumptions about how Apps Script
// exposes it, and a wrong guess here silently makes every item look like a mismatch.
function kindOf(item) {
  const t = item.getType();
  if (t === FormApp.ItemType.LIST) return "LIST";
  if (t === FormApp.ItemType.MULTIPLE_CHOICE) return "MULTIPLE_CHOICE";
  if (t === FormApp.ItemType.CHECKBOX) return "CHECKBOX";
  if (t === FormApp.ItemType.TEXT) return "TEXT";
  if (t === FormApp.ItemType.PARAGRAPH_TEXT) return "PARAGRAPH_TEXT";
  return "OTHER";
}

// getItems() hands back generic Items; each has to be cast to its own type before it will
// take a title, help text or choices.
function typedItem(item, kind) {
  if (kind === "LIST") return item.asListItem();
  if (kind === "MULTIPLE_CHOICE") return item.asMultipleChoiceItem();
  if (kind === "CHECKBOX") return item.asCheckboxItem();
  if (kind === "TEXT") return item.asTextItem();
  return item.asParagraphTextItem();
}

function newItem(form, kind) {
  if (kind === "LIST") return form.addListItem();
  if (kind === "MULTIPLE_CHOICE") return form.addMultipleChoiceItem();
  if (kind === "CHECKBOX") return form.addCheckboxItem();
  if (kind === "TEXT") return form.addTextItem();
  return form.addParagraphTextItem();
}

function configure(item, q) {
  item.setTitle(q.title);
  item.setHelpText(q.help);
  if (q.choices) item.setChoiceValues(q.choices);
  item.setRequired(q.required);
}

function setup() {
  const form = findExistingForm() || FormApp.create(TITLE);
  form.setTitle(TITLE);
  form.setDescription(DESCRIPTION);
  // Email collection is what lets you chase non-responders; ingest derives a
  // handle from the address and discards it. Not every account type allows it,
  // and a refusal here must not abandon a half-built form.
  try { form.setCollectEmail(true); }
  catch (e) { Logger.log("Could not turn on email collection: " + e.message); }
  try { form.setLimitOneResponsePerUser(false); form.setProgressBar(true); }
  catch (e) { Logger.log("Could not set response options: " + e.message); }

  // Update the questions IN PLACE whenever the shape still matches.
  //
  // Deleting an item does NOT delete its column in the responses sheet: the old column keeps
  // its answers and its heading, and re-adding the question appends a SECOND column with the
  // same heading. A CSV export then has two identical headings and the empty one wins.
  // Adding an industry to the dropdown must not cost you the answers you already collected.
  const existing = form.getItems();
  let sameShape = existing.length === QUESTIONS.length;
  for (let i = 0; sameShape && i < QUESTIONS.length; i++) {
    if (kindOf(existing[i]) !== QUESTIONS[i].kind) sameShape = false;
  }

  if (sameShape) {
    for (let i = 0; i < QUESTIONS.length; i++) {
      configure(typedItem(existing[i], QUESTIONS[i].kind), QUESTIONS[i]);
    }
    Logger.log("Updated " + QUESTIONS.length + " question(s) in place; response columns kept.");
  } else {
    if (existing.length) {
      Logger.log("The questionnaire's shape changed (" + existing.length + " item(s) -> " +
        QUESTIONS.length + "), so the questions were rebuilt rather than updated.");
      Logger.log("Columns already in the responses sheet keep their answers, but the rebuilt");
      Logger.log("questions start new, empty columns with the same headings. If this form has");
      Logger.log("responses you have not ingested yet, export the sheet before trusting it.");
    }
    for (let i = existing.length - 1; i >= 0; i--) form.deleteItem(existing[i]);
    for (let i = 0; i < QUESTIONS.length; i++) configure(newItem(form, QUESTIONS[i].kind), QUESTIONS[i]);
  }

  // Responses go to their own spreadsheet; ingest reads a CSV export of it.
  //
  // getDestinationId() THROWS when nothing is linked yet — it does not return null — so it
  // cannot be used as a condition. Probing it any other way is the same bug in a new shape.
  let destination = null;
  try { destination = form.getDestinationId(); } catch (e) { destination = null; }
  if (!destination) {
    const sheet = SpreadsheetApp.create(TITLE + " — responses");
    form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());
    destination = sheet.getId();
    Logger.log("Responses sheet created: " + sheet.getUrl());
  } else {
    Logger.log("Responses sheet: " +
      SpreadsheetApp.openById(destination).getUrl());
  }
  Logger.log("");
  Logger.log("=== PASTE THIS INTO SLACK ===");
  Logger.log(form.getPublishedUrl());
  Logger.log("");
  Logger.log("Edit the form: " + form.getEditUrl());
}
