// GENERATED by `ctsx collect:render` from collector/questions/expert-intake.yaml v1
// — do not edit. Paste into script.google.com, then Run > setup.
//
// Creates (or reuses) the Grocery & q-commerce intake form and its responses spreadsheet, and
// prints the URL to paste into Slack. Runs as you, under your own Workspace account:
// no Cloud project, no OAuth client, no admin approval.

const TITLE = "commercetools spec collector — Grocery & q-commerce";

function setup() {
  const existing = DriveApp.getFilesByName(TITLE);
  const form = existing.hasNext()
    ? FormApp.openById(existing.next().getId())
    : FormApp.create(TITLE);
  form.setDescription("What would you add to a bare storefront to make it work for Grocery & q-commerce? Three boxes, about three minutes. Your answers become reviewed spec drafts. Please do not name a customer you are under NDA with — describe the pattern instead.");
  form.setCollectEmail(true);          // Workspace only; drives who-has-answered, then discarded at ingest
  form.setLimitOneResponsePerUser(false);
  form.setProgressBar(true);

  // Rebuild the items so the form always matches the questionnaire it was generated from.
  const items = form.getItems();
  for (let i = items.length - 1; i >= 0; i--) form.deleteItem(items[i]);

  form.addMultipleChoiceItem().setTitle("How deep is your Grocery & q-commerce experience?").setChoiceValues(["Built it","Sold it","Advised on it","Read about it"]).setRequired(true);
  form.addCheckboxItem().setTitle("Which business models have you seen Grocery & q-commerce run as?").setChoiceValues(["B2C","B2B","B2B2C","B2B2B"]).setRequired(true);
  form.addParagraphTextItem().setTitle("Feature 1: what would you add to a bare storefront to make it work for Grocery & q-commerce?").setHelpText("One capability per box. Name it, then say why Grocery & q-commerce specifically needs it.").setRequired(true);
  form.addParagraphTextItem().setTitle("Feature 2: what would you add to a bare storefront to make it work for Grocery & q-commerce?").setHelpText("One capability per box. Name it, then say why Grocery & q-commerce specifically needs it.").setRequired(false);
  form.addParagraphTextItem().setTitle("Feature 3: what would you add to a bare storefront to make it work for Grocery & q-commerce?").setHelpText("One capability per box. Name it, then say why Grocery & q-commerce specifically needs it.").setRequired(false);
  form.addCheckboxItem().setTitle("Which areas do your features touch?").setChoiceValues(["Catalog & product data","Search & discovery","Cart & basket","Pricing & promotions","Checkout & payment","Shipping & fulfillment","Order management","Customers & accounts"]).setRequired(false);
  form.addTextItem().setTitle("A retailer or competitor doing this well (optional)").setHelpText("No customer names under NDA — describe the pattern instead.").setRequired(false);

  // Responses go to their own spreadsheet; ingest reads a CSV export of it.
  if (!form.getDestinationId()) {
    const sheet = SpreadsheetApp.create(TITLE + " — responses");
    form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());
    Logger.log("Responses sheet: " + sheet.getUrl());
  }
  Logger.log("Share this link: " + form.getPublishedUrl());
  Logger.log("Edit the form:   " + form.getEditUrl());
}
