// ============================================================================
//  DO NOT DEPLOY THIS. It is not a web app.
//
//  Run it once, from this editor:
//    1. pick `setup` in the function dropdown next to the Run button
//    2. click Run, and allow the authorization prompt (Forms, Drive, Sheets)
//    3. read the URL out of the Execution log at the bottom
//
//  Deploy > New deployment is the wrong path: a web app needs a doGet(e),
//  this has none, and you get "Script function not found: doGet".
//  This script CREATES a Google Form. The form has the URL you share; the
//  script is only what builds it, and it is finished the moment it has run.
// ============================================================================
//
// GENERATED by `ctsx collect:render` from collector/questions/expert-intake.yaml v1
// — do not edit. Regenerate instead.
//
// Creates (or reuses) the Telecommunications intake form and its responses spreadsheet.
// Runs as you, under your own account: no Cloud project, no OAuth client, no
// admin approval. Re-running is safe — it finds the form by title rather than
// making a second one.

const TITLE = "commercetools spec collector — Telecommunications";

function setup() {
  const existing = DriveApp.getFilesByName(TITLE);
  const form = existing.hasNext()
    ? FormApp.openById(existing.next().getId())
    : FormApp.create(TITLE);
  form.setDescription("What would you add to a bare storefront to make it work for Telecommunications? Three boxes, about three minutes. Your answers become reviewed spec drafts. Please do not name a customer you are under NDA with — describe the pattern instead.");
  // Email collection is what lets you chase non-responders; ingest derives a
  // handle from the address and discards it. Not every account type allows it,
  // and a refusal here must not abandon a half-built form.
  try { form.setCollectEmail(true); }
  catch (e) { Logger.log("Could not turn on email collection: " + e.message); }
  try { form.setLimitOneResponsePerUser(false); form.setProgressBar(true); }
  catch (e) { Logger.log("Could not set response options: " + e.message); }

  // Rebuild the items so the form always matches the questionnaire it was generated from.
  const items = form.getItems();
  for (let i = items.length - 1; i >= 0; i--) form.deleteItem(items[i]);

  form.addCheckboxItem().setTitle("Which business models have you seen Telecommunications run as?").setChoiceValues(["B2C","B2B","B2B2C","B2B2B"]).setRequired(true);
  form.addParagraphTextItem().setTitle("Feature 1: what would you add to a bare storefront to make it work for Telecommunications?").setHelpText("One capability per box. Name it, then say why Telecommunications specifically needs it.").setRequired(true);
  form.addParagraphTextItem().setTitle("Feature 2: what would you add to a bare storefront to make it work for Telecommunications?").setHelpText("One capability per box. Name it, then say why Telecommunications specifically needs it.").setRequired(false);
  form.addParagraphTextItem().setTitle("Feature 3: what would you add to a bare storefront to make it work for Telecommunications?").setHelpText("One capability per box. Name it, then say why Telecommunications specifically needs it.").setRequired(false);
  form.addCheckboxItem().setTitle("Which areas do your features touch?").setChoiceValues(["Catalog & product data","Search & discovery","Cart & basket","Pricing & promotions","Checkout & payment","Shipping & fulfillment","Order management","Customers & accounts","Other"]).setRequired(false);
  form.addTextItem().setTitle("A retailer or competitor doing this well (optional)").setHelpText("No customer names under NDA — describe the pattern instead.").setRequired(false);

  // Responses go to their own spreadsheet; ingest reads a CSV export of it.
  if (!form.getDestinationId()) {
    const sheet = SpreadsheetApp.create(TITLE + " — responses");
    form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId());
    Logger.log("Responses sheet: " + sheet.getUrl());
  }
  Logger.log("");
  Logger.log("=== PASTE THIS INTO SLACK ===");
  Logger.log(form.getPublishedUrl());
  Logger.log("");
  Logger.log("Edit the form: " + form.getEditUrl());
}
